# Generated by Django 5.1.6 on 2025-02-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='video',
        ),
        migrations.AddField(
            model_name='news',
            name='File',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
